name: 🐛 버그 제보
description: 기능이 제대로 작동하지 않나요?
title: '<제목>'
labels: '버그'
body:
- type: textarea
  attributes:
    label: 어떤 기능의 어떤 부분에 버그가 있나요?
- type: dropdown
  attributes:
    label: 버그가 일어나는 화면
    description: 버그가 일어나는 화면을 선택해주세요.
    multiple: false
    options:
      - '급식 화면'
      - '학교 선택 화면'
      - '재료 검색 화면'
      - '재료 정보 화면'
      - '설정 화면'
      - '기타'
- type: textarea
  attributes:
    label: 버그가 언제 어떻게 일어나나요?
    placeholder: |
      1. 어떤 화면에서...
      2. 이 버튼을 누르면...
      3. 원래는 이렇게 되어야 하지만...
- type: textarea
  attributes:
    label: 추가 정보
    description: 기능을 구현할 때 도움이 되는 정보가 있다면 알려주세요.
