name: 💄 디자인 개선
description: 버튼의 배치, 글자 크기, 배열 등도 디자인이랍니다.
title: '<제목>'
labels: '디자인'
body:
- type: textarea
  attributes:
    label: 어떤 기능의 디자인이 개선되면 좋을까요?
- type: dropdown
  attributes:
    label: 개선이 필요한 화면
    description: 개선이 필요한 화면을 선택해주세요.
    multiple: false
    options:
      - '급식 화면'
      - '학교 선택 화면'
      - '기타'
- type: textarea
  attributes:
    label: 현재 디자인의 어떤 점이 문제인가요?
    description: 여기서 '문제'는 '개선되면 좋을 것 같다'는 뜻입니다.
- type: textarea
  attributes:
    label: 현재 디자인이 어떻게 개선되면 좋을까요?
- type: textarea
  attributes:
    label: 개선된다면 기능을 어떻게 사용할 수 있나요?
    description: 사용하는 과정이 달라졌을 때만 적어주세요.
    placeholder: |
      1. 어떤 화면에서...
      2. 이 버튼을 누르고...
      3. 원래는 이렇게 해야 했지만 이렇게 하면...
  validations:
    required: false
- type: textarea
  attributes:
    label: 추가 정보
    description: 기능을 구현할 때 도움이 되는 정보가 있다면 알려주세요.
