name: 🔧 기능 개선
description: 현재 기능이 불편한가요?
title: '<제목>'
labels: '기능'
body:
- type: textarea
  attributes:
    label: 어떤 기능의 어떤 부분이 불편한가요?
- type: dropdown
  attributes:
    label: 개선할 기능이 있는 화면
    description: 개선할 기능이 있는 화면을 선택해주세요.
    multiple: false
    options:
      - '급식 화면'
      - '학교 선택 화면'
      - '재료 검색 화면'
      - '재료 정보 화면'
      - '설정 화면'
      - '기타'
- type: textarea
  attributes:
    label: 현재 기능이 어떻게 개선되면 좋을까요?
- type: textarea
  attributes:
    label: 개선된다면 기능을 어떻게 사용할 수 있나요?
    placeholder: |
      1. 어떤 화면에서...
      2. 이 버튼을 누르고...
      3. 원래는 이렇게 해야 했지만 이렇게 하면...
- type: textarea
  attributes:
    label: 추가 정보
    description: 기능을 구현할 때 도움이 되는 정보가 있다면 알려주세요.
